title: Githen Ronney
logo: /assets/img/Screenshot 2022-09-17 070301.png
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/githen-ronney-08ba6015/">LinkedIn</a> |
  <a href="https://github.com/GITHENR">GitHub</a>
  
  <br>   
  I am a data evangelist helps organizations to realise true potential of 
  data in data driven decision making.
  <br>
  </p>



theme: jekyll-theme-minimal
